# Generated by Codex on 2025-11-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_payment_amount_alter_payment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='confirmation_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на оплату'),
        ),
        migrations.AddField(
            model_name='payment',
            name='idempotence_key',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Idempotence ключ'),
        ),
    ]
