# Generated by Django 4.2.7 on 2025-11-19 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportcompany',
            name='api_account',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='API Account (CDEK)'),
        ),
        migrations.AddField(
            model_name='transportcompany',
            name='api_secure_password',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='API Secure Password (CDEK)'),
        ),
        migrations.AddField(
            model_name='transportcompany',
            name='api_type',
            field=models.CharField(choices=[('internal', 'Внутренний расчет'), ('cdek', 'CDEK API')], default='internal', max_length=20, verbose_name='Тип интеграции'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Базовая цена'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='max_weight',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Максимальный вес (кг)'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='min_weight',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Минимальный вес (кг)'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='price_per_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена за кг'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='transport_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='tariffs.transportcompany', verbose_name='Транспортная компания'),
        ),
        migrations.AlterField(
            model_name='transportcompany',
            name='api_url',
            field=models.URLField(blank=True, null=True, verbose_name='API URL'),
        ),
        migrations.AlterField(
            model_name='transportcompany',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='transportcompany',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='transportcompany',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='transportcompany',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
