# Generated by Django 4.2.7 on 2025-11-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0002_transportcompany_api_account_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transportcompany',
            options={'ordering': ['name'], 'verbose_name': 'Транспортная компания', 'verbose_name_plural': 'Транспортные компании'},
        ),
        migrations.AddField(
            model_name='transportcompany',
            name='default_tariff_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Код тарифа CDEK по умолчанию'),
        ),
        migrations.AddField(
            model_name='transportcompany',
            name='default_tariff_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название тарифа по умолчанию'),
        ),
    ]
