# Generated by Django 4.2.7 on 2025-12-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0003_alter_transportcompany_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportcompany',
            name='api_developer_key',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Developer Key (CDEK) - для работы от третьих лиц'),
        ),
    ]
