# Generated by Django 4.2.7 on 2025-12-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0004_add_developer_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportcompany',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Логотип'),
        ),
    ]
