# Generated by Django 4.2.7 on 2025-12-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0005_transportcompany_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportcompany',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='company_logos/', verbose_name='Логотип'),
        ),
    ]
