# Generated by Django 4.2.7 on 2025-12-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0006_alter_transportcompany_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='delivery_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Срок доставки (дней)'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='delivery_days_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимальный срок доставки (дней)'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='delivery_days_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Минимальный срок доставки (дней)'),
        ),
    ]
