# Generated by Django 4.2.7 on 2025-12-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0007_tariff_delivery_days_tariff_delivery_days_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='courier_delivery_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Дополнительная стоимость за доставку курьером'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='courier_delivery_supported',
            field=models.BooleanField(default=False, verbose_name='Поддерживает доставку курьером'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='courier_pickup_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Дополнительная стоимость за забор курьером'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='courier_pickup_supported',
            field=models.BooleanField(default=False, verbose_name='Поддерживает забор курьером'),
        ),
    ]
