# Generated by Django 4.2.7 on 2025-12-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_created_at_alter_user_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sender_company',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название компании отправителя'),
        ),
        migrations.AddField(
            model_name='user',
            name='sender_contragent_type',
            field=models.CharField(blank=True, choices=[('LEGAL_ENTITY', 'Юридическое лицо'), ('INDIVIDUAL', 'Физическое лицо')], max_length=20, null=True, verbose_name='Тип контрагента отправителя'),
        ),
        migrations.AddField(
            model_name='user',
            name='sender_tin',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ИНН отправителя'),
        ),
    ]
