# Generated by Django 4.2.7 on 2025-11-19 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='external_order_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер заказа во внешней системе'),
        ),
        migrations.AddField(
            model_name='order',
            name='external_order_uuid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='UUID заказа во внешней системе'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Высота (см)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Длина (см)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='order',
            name='recipient_address',
            field=models.TextField(verbose_name='Адрес получателя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='recipient_city',
            field=models.CharField(max_length=100, verbose_name='Город получателя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='recipient_name',
            field=models.CharField(max_length=200, verbose_name='Имя получателя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='recipient_phone',
            field=models.CharField(max_length=20, verbose_name='Телефон получателя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sender_address',
            field=models.TextField(verbose_name='Адрес отправителя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sender_city',
            field=models.CharField(max_length=100, verbose_name='Город отправителя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sender_name',
            field=models.CharField(max_length=200, verbose_name='Имя отправителя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sender_phone',
            field=models.CharField(max_length=20, verbose_name='Телефон отправителя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('pending_payment', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('in_delivery', 'В доставке'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='transport_company_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID транспортной компании'),
        ),
        migrations.AlterField(
            model_name='order',
            name='transport_company_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название транспортной компании'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='order',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вес (кг)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ширина (см)'),
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Создан'), ('status_changed', 'Изменен статус'), ('payment_received', 'Получена оплата'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен'), ('cancelled', 'Отменен')], max_length=20, verbose_name='Тип события'),
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Метаданные'),
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.order', verbose_name='Заказ'),
        ),
    ]
