# Generated by Django 4.2.7 on 2025-11-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_external_order_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tariff_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Код тарифа (CDEK)'),
        ),
        migrations.AddField(
            model_name='order',
            name='tariff_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название тарифа'),
        ),
    ]
