# Generated by Django 4.2.7 on 2025-11-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_tariff_code_order_tariff_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='recipient_delivery_point_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Код ПВЗ получателя'),
        ),
    ]
