# Generated by Django 4.2.7 on 2025-12-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_sender_company_order_sender_contragent_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='package_image',
            field=models.ImageField(blank=True, null=True, upload_to='package_images/', verbose_name='Фото посылки'),
        ),
    ]
