# Generated by Django 4.2.7 on 2025-12-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_package_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='recipient_delivery_point_address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес ПВЗ получателя'),
        ),
    ]
