# Generated by Django 4.2.7 on 2025-12-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_recipient_delivery_point_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='needs_packaging',
            field=models.BooleanField(default=False, verbose_name='Требуется упаковка'),
        ),
    ]
