# Generated by Django 4.2.7 on 2025-12-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_needs_packaging'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packaging_price', models.DecimalField(decimal_places=2, default=50, max_digits=10, verbose_name='Стоимость упаковки (₽)')),
                ('pochtahub_commission', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Комиссия PochtaHub (₽)')),
                ('acquiring_percent', models.DecimalField(decimal_places=2, default=3.0, max_digits=5, verbose_name='Процент эквайринга (%)')),
                ('insurance_price', models.DecimalField(decimal_places=2, default=10, max_digits=10, verbose_name='Стоимость страховки (₽)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Настройки приложения',
                'verbose_name_plural': 'Настройки приложения',
                'db_table': 'app_settings',
            },
        ),
    ]
