# Generated by Django 4.2.7 on 2025-12-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_appsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='acquiring_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость эквайринга'),
        ),
        migrations.AddField(
            model_name='order',
            name='insurance_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость страховки'),
        ),
        migrations.AddField(
            model_name='order',
            name='packaging_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость упаковки'),
        ),
        migrations.AddField(
            model_name='order',
            name='pochtahub_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Комиссия PochtaHub'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Итоговая стоимость'),
        ),
    ]
