# Generated by Django 4.2.7 on 2025-12-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_acquiring_price_order_insurance_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email получателя'),
        ),
        migrations.AddField(
            model_name='order',
            name='sender_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email отправителя'),
        ),
    ]
