# Generated by Django 4.2.7 on 2026-02-24 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('business_page_view', 'Просмотр business-страницы'), ('business_login_success', 'Успешный вход'), ('business_photo_uploaded', 'Загрузка фото'), ('business_calc_success', 'Успешный расчет'), ('business_calc_error', 'Ошибка расчета'), ('business_copy_dimensions', 'Копирование габаритов'), ('business_share', 'Поделиться результатом')], max_length=64, verbose_name='Тип события')),
                ('source', models.CharField(default='business', max_length=32, verbose_name='Источник')),
                ('client_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Клиентское время')),
                ('count_photos', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество фото')),
                ('result', models.JSONField(blank=True, default=dict, verbose_name='Результат')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Метаданные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_events', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Событие business',
                'verbose_name_plural': 'События business',
                'db_table': 'business_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='business_ev_event_t_9534bd_idx'), models.Index(fields=['source', 'created_at'], name='business_ev_source_c00cf8_idx'), models.Index(fields=['user', 'created_at'], name='business_ev_user_id_b9a1e1_idx')],
            },
        ),
    ]
