# Generated by Django 4.2.7 on 2026-02-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessevent',
            name='anonymous_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Анонимный ID'),
        ),
        migrations.AddField(
            model_name='businessevent',
            name='device',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Тип устройства'),
        ),
        migrations.AddField(
            model_name='businessevent',
            name='duration_ms',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность, мс'),
        ),
        migrations.AddField(
            model_name='businessevent',
            name='error_code',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Код ошибки'),
        ),
        migrations.AddField(
            model_name='businessevent',
            name='error_message',
            field=models.TextField(blank=True, default='', verbose_name='Сообщение ошибки'),
        ),
        migrations.AddField(
            model_name='businessevent',
            name='event_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Уникальный ID события'),
        ),
        migrations.AddField(
            model_name='businessevent',
            name='ip_hash',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Хеш IP'),
        ),
        migrations.AddField(
            model_name='businessevent',
            name='ip_prefix',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Префикс IP'),
        ),
        migrations.AddField(
            model_name='businessevent',
            name='path',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Путь страницы'),
        ),
        migrations.AddField(
            model_name='businessevent',
            name='referrer',
            field=models.TextField(blank=True, default='', verbose_name='Referrer'),
        ),
        migrations.AddField(
            model_name='businessevent',
            name='session_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='ID сессии'),
        ),
        migrations.AddField(
            model_name='businessevent',
            name='user_agent',
            field=models.TextField(blank=True, default='', verbose_name='User agent'),
        ),
        migrations.AddField(
            model_name='businessevent',
            name='utm_campaign',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='UTM campaign'),
        ),
        migrations.AddField(
            model_name='businessevent',
            name='utm_content',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='UTM content'),
        ),
        migrations.AddField(
            model_name='businessevent',
            name='utm_medium',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='UTM medium'),
        ),
        migrations.AddField(
            model_name='businessevent',
            name='utm_source',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='UTM source'),
        ),
        migrations.AddField(
            model_name='businessevent',
            name='utm_term',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='UTM term'),
        ),
        migrations.AddField(
            model_name='businessevent',
            name='viewport_height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Высота viewport'),
        ),
        migrations.AddField(
            model_name='businessevent',
            name='viewport_width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ширина viewport'),
        ),
        migrations.AddIndex(
            model_name='businessevent',
            index=models.Index(fields=['anonymous_id', 'created_at'], name='business_ev_anonymo_0bad09_idx'),
        ),
        migrations.AddIndex(
            model_name='businessevent',
            index=models.Index(fields=['session_id', 'created_at'], name='business_ev_session_abb4fe_idx'),
        ),
        migrations.AddIndex(
            model_name='businessevent',
            index=models.Index(fields=['ip_hash', 'created_at'], name='business_ev_ip_hash_e26d10_idx'),
        ),
        migrations.AddIndex(
            model_name='businessevent',
            index=models.Index(fields=['ip_prefix', 'created_at'], name='business_ev_ip_pref_68e46e_idx'),
        ),
    ]
